services:

  simple-example-api-database:
    image: postgres:15.6
    container_name: simple-example-api-database
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - simple-example-api-database-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pg-data:
    driver: local

networks:
  simple-example-api-database-network: