spring:
  application:
    name: simple-example-api

  liquibase:
    change-log: classpath:database/liquibase-changelog.yml
    url: \${DATABASE_URL:jdbc:postgresql://localhost:5432/simple-example-api}
    user: \${DATABASE_USERNAME:postgres}
    password: \${DATABASE_PASSWORD:postgres}
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: \${DATABASE_URL:jdbc:postgresql://localhost:5432/simple-example-api}
    username: \${DATABASE_USERNAME:postgres}
    password: \${DATABASE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    defer-datasource-initialization: false

  sql:
    init:
      mode: never

  output:
    ansi:
      enabled: always

app:
  version: ${version}
  name: \${spring.application.name}
  description: ${description}

server:
  port: 8090
  servlet:
    context-path: \${CONTEXT_PATH:/}

springdoc:
  swagger-ui:
    doc-expansion: none  # controller do not display by default

