name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  docker:
    uses: ./.github/workflows/docker-publish.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
